services:
  server:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - REDIS_HOST=redis
      - ROOT_DOMAIN=localhost

  redis:
    image: redis:7.2.4
    ports:
      - "6379:6379"
    command: redis-server --loglevel notice
    volumes:
      - redis_data:/data

volumes:
  redis_data:
